import { Unit } from "./unit"

export interface IProduct {
id?: number,
name: string,
code: string,
type_barcode: string,
brand_id: number,
product_id: number,
unit_id: number,
tax_method: string,
tax_cost:number,
tax_type:string,
product_tax: number,
fixed_price: number,
price: number,
fixed_cost: number,
cost: number,
stockalert:string,
image:string,
unit_sale_id: number,
unit_purchase_id: number,
is_variant: boolean,
category_id?: number,
category?:any,
brand?: string,
unit:Unit,
}
